#----------------------------------------------------------------------------
# Run the templates.
#----------------------------------------------------------------------------
apply "set_up_git.rb"
apply "set_up_capistrano.rb"
apply "set_up_testing.rb"
apply "remove_the_usual_cruft.rb"
apply "set_up_mysql2.rb"
apply "add_application_css_and_js.rb"
apply "set_up_960_gridder.rb"
apply "set_up_haml.rb"
apply "set_up_simple_form.rb"
apply "set_up_flutie.rb"
apply "set_up_high_voltage.rb"
apply "set_up_will_paginate.rb"
apply "depify_me.rb"
apply "set_up_whenever.rb"
apply "set_up_bwi_base.rb"
apply "add_scaffold_generator_templates.rb"
apply "set_up_devise.rb"
apply "set_up_cancan.rb"
apply "set_up_optional_gems.rb"
