require File.join(File.dirname(__FILE__), 'rails_extensions.rb')

apply recipe('git')
apply recipe('testing')
apply recipe('remove_the_usual_cruft')
apply recipe('mysql2')
apply recipe('haml')
apply recipe('simple_form')
apply recipe('add_scaffold_generator_templates')
apply recipe('devise')
apply recipe('cancan')
apply recipe('optional_gems')
