source :rubygems

gem 'rails', '~> 3.2.0'

# DBMS
gem 'sqlite3'
gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'haml-rails'
  gem 'twitter-bootstrap-rails'
  gem 'jquery-rails'

  gem 'uglifier', '>= 1.0.3'
end

# Deploy with capistrano
gem 'capistrano'

group :production do
  gem 'unicorn'
end
